---
- name: Set up database server
  hosts: db
  become: true
  roles:
    - db

- name: Set up application server
  hosts: app
  become: true
  roles:
    - app

- name: Set up web server (Nginx)
  hosts: web
  become: true
  roles:
    - web